### ISSUE TITLE
Add map color attribute for items.

### ISSUE THREAD

**Issue by zimage** [Sgambe33/MinecraftAPI#1]
It'd be nice to be able to query an item and get the color it is on a map. The colors are detailed on the wiki

https://minecraft.fandom.com/wiki/Map_item_format?action=edit&section=9

**Comment by Sgambe33** [comment]
> It'd be nice to be able to query an item and get the color it is on a map. The colors are detailed on the wiki
> 
> https://minecraft.fandom.com/wiki/Map_item_format?action=edit&section=9

I'm sorry but the project Is being discontinued due to lack of interest and time.
